# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution_state.proto',
  package='heron.proto.system',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x65xecution_state.proto\x12\x12heron.proto.system\"[\n\x11HeronReleaseState\x12\x18\n\x10release_username\x18\x01 \x01(\t\x12\x13\n\x0brelease_tag\x18\x02 \x01(\t\x12\x17\n\x0frelease_version\x18\x03 \x01(\t\"\xdc\x01\n\x0e\x45xecutionState\x12\x15\n\rtopology_name\x18\x01 \x02(\t\x12\x13\n\x0btopology_id\x18\x02 \x02(\t\x12\x17\n\x0fsubmission_time\x18\x03 \x01(\x03\x12\x17\n\x0fsubmission_user\x18\x04 \x01(\t\x12\x0f\n\x07\x63luster\x18\x05 \x02(\t\x12\x0f\n\x07\x65nviron\x18\x06 \x02(\t\x12\x0c\n\x04role\x18\x07 \x02(\t\x12<\n\rrelease_state\x18\x08 \x01(\x0b\x32%.heron.proto.system.HeronReleaseStateB6\n\x1e\x63om.twitter.heron.proto.systemB\x14\x45xecutionEnvironment')
)




_HERONRELEASESTATE = _descriptor.Descriptor(
  name='HeronReleaseState',
  full_name='heron.proto.system.HeronReleaseState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='release_username', full_name='heron.proto.system.HeronReleaseState.release_username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='release_tag', full_name='heron.proto.system.HeronReleaseState.release_tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='release_version', full_name='heron.proto.system.HeronReleaseState.release_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=136,
)


_EXECUTIONSTATE = _descriptor.Descriptor(
  name='ExecutionState',
  full_name='heron.proto.system.ExecutionState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.system.ExecutionState.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topology_id', full_name='heron.proto.system.ExecutionState.topology_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='submission_time', full_name='heron.proto.system.ExecutionState.submission_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='submission_user', full_name='heron.proto.system.ExecutionState.submission_user', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster', full_name='heron.proto.system.ExecutionState.cluster', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='environ', full_name='heron.proto.system.ExecutionState.environ', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='heron.proto.system.ExecutionState.role', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='release_state', full_name='heron.proto.system.ExecutionState.release_state', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=359,
)

_EXECUTIONSTATE.fields_by_name['release_state'].message_type = _HERONRELEASESTATE
DESCRIPTOR.message_types_by_name['HeronReleaseState'] = _HERONRELEASESTATE
DESCRIPTOR.message_types_by_name['ExecutionState'] = _EXECUTIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeronReleaseState = _reflection.GeneratedProtocolMessageType('HeronReleaseState', (_message.Message,), dict(
  DESCRIPTOR = _HERONRELEASESTATE,
  __module__ = 'execution_state_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronReleaseState)
  ))
_sym_db.RegisterMessage(HeronReleaseState)

ExecutionState = _reflection.GeneratedProtocolMessageType('ExecutionState', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTIONSTATE,
  __module__ = 'execution_state_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.ExecutionState)
  ))
_sym_db.RegisterMessage(ExecutionState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.twitter.heron.proto.systemB\024ExecutionEnvironment'))
# @@protoc_insertion_point(module_scope)
