# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: physical_plan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import topology_pb2 as topology__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='physical_plan.proto',
  package='heron.proto.system',
  syntax='proto2',
  serialized_pb=_b('\n\x13physical_plan.proto\x12\x12heron.proto.system\x1a\x0etopology.proto\"\x98\x01\n\x05StMgr\x12\n\n\x02id\x18\x01 \x02(\t\x12\x11\n\thost_name\x18\x02 \x02(\t\x12\x11\n\tdata_port\x18\x03 \x02(\x05\x12\x17\n\x0flocal_data_port\x18\x08 \x01(\x05\x12\x16\n\x0elocal_endpoint\x18\x04 \x02(\t\x12\x0b\n\x03\x63wd\x18\x05 \x01(\t\x12\x0b\n\x03pid\x18\x06 \x01(\x05\x12\x12\n\nshell_port\x18\x07 \x01(\x05\"~\n\x0cInstanceInfo\x12\x0f\n\x07task_id\x18\x01 \x02(\x05\x12\x17\n\x0f\x63omponent_index\x18\x02 \x02(\x05\x12\x16\n\x0e\x63omponent_name\x18\x03 \x02(\t\x12\x0e\n\x06params\x18\x04 \x03(\t\x12\x1c\n\x14remote_debugger_port\x18\x05 \x01(\x05\"a\n\x08Instance\x12\x13\n\x0binstance_id\x18\x01 \x02(\t\x12\x10\n\x08stmgr_id\x18\x02 \x02(\t\x12.\n\x04info\x18\x03 \x02(\x0b\x32 .heron.proto.system.InstanceInfo\"\x97\x01\n\x0cPhysicalPlan\x12+\n\x08topology\x18\x01 \x02(\x0b\x32\x19.heron.proto.api.Topology\x12)\n\x06stmgrs\x18\x02 \x03(\x0b\x32\x19.heron.proto.system.StMgr\x12/\n\tinstances\x18\x03 \x03(\x0b\x32\x1c.heron.proto.system.InstanceB/\n\x1e\x63om.twitter.heron.proto.systemB\rPhysicalPlans')
  ,
  dependencies=[topology__pb2.DESCRIPTOR,])




_STMGR = _descriptor.Descriptor(
  name='StMgr',
  full_name='heron.proto.system.StMgr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='heron.proto.system.StMgr.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_name', full_name='heron.proto.system.StMgr.host_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_port', full_name='heron.proto.system.StMgr.data_port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_data_port', full_name='heron.proto.system.StMgr.local_data_port', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_endpoint', full_name='heron.proto.system.StMgr.local_endpoint', index=4,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cwd', full_name='heron.proto.system.StMgr.cwd', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='heron.proto.system.StMgr.pid', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shell_port', full_name='heron.proto.system.StMgr.shell_port', index=7,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=212,
)


_INSTANCEINFO = _descriptor.Descriptor(
  name='InstanceInfo',
  full_name='heron.proto.system.InstanceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='heron.proto.system.InstanceInfo.task_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_index', full_name='heron.proto.system.InstanceInfo.component_index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_name', full_name='heron.proto.system.InstanceInfo.component_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='heron.proto.system.InstanceInfo.params', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_debugger_port', full_name='heron.proto.system.InstanceInfo.remote_debugger_port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=340,
)


_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='heron.proto.system.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='heron.proto.system.Instance.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgr_id', full_name='heron.proto.system.Instance.stmgr_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='heron.proto.system.Instance.info', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=439,
)


_PHYSICALPLAN = _descriptor.Descriptor(
  name='PhysicalPlan',
  full_name='heron.proto.system.PhysicalPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology', full_name='heron.proto.system.PhysicalPlan.topology', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgrs', full_name='heron.proto.system.PhysicalPlan.stmgrs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instances', full_name='heron.proto.system.PhysicalPlan.instances', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=593,
)

_INSTANCE.fields_by_name['info'].message_type = _INSTANCEINFO
_PHYSICALPLAN.fields_by_name['topology'].message_type = topology__pb2._TOPOLOGY
_PHYSICALPLAN.fields_by_name['stmgrs'].message_type = _STMGR
_PHYSICALPLAN.fields_by_name['instances'].message_type = _INSTANCE
DESCRIPTOR.message_types_by_name['StMgr'] = _STMGR
DESCRIPTOR.message_types_by_name['InstanceInfo'] = _INSTANCEINFO
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['PhysicalPlan'] = _PHYSICALPLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StMgr = _reflection.GeneratedProtocolMessageType('StMgr', (_message.Message,), dict(
  DESCRIPTOR = _STMGR,
  __module__ = 'physical_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.StMgr)
  ))
_sym_db.RegisterMessage(StMgr)

InstanceInfo = _reflection.GeneratedProtocolMessageType('InstanceInfo', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCEINFO,
  __module__ = 'physical_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.InstanceInfo)
  ))
_sym_db.RegisterMessage(InstanceInfo)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCE,
  __module__ = 'physical_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.Instance)
  ))
_sym_db.RegisterMessage(Instance)

PhysicalPlan = _reflection.GeneratedProtocolMessageType('PhysicalPlan', (_message.Message,), dict(
  DESCRIPTOR = _PHYSICALPLAN,
  __module__ = 'physical_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.PhysicalPlan)
  ))
_sym_db.RegisterMessage(PhysicalPlan)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.twitter.heron.proto.systemB\rPhysicalPlans'))
# @@protoc_insertion_point(module_scope)
