# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import packing_plan_pb2 as packing__plan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler.proto',
  package='heron.proto.scheduler',
  syntax='proto2',
  serialized_pb=_b('\n\x0fscheduler.proto\x12\x15heron.proto.scheduler\x1a\x0c\x63ommon.proto\x1a\x12packing_plan.proto\"X\n\x11SchedulerLocation\x12\x15\n\rtopology_name\x18\x01 \x02(\t\x12\x15\n\rhttp_endpoint\x18\x02 \x02(\t\x12\x15\n\rjob_page_link\x18\x03 \x03(\t\",\n\x13KillTopologyRequest\x12\x15\n\rtopology_name\x18\x01 \x02(\t\"H\n\x16RestartTopologyRequest\x12\x15\n\rtopology_name\x18\x01 \x02(\t\x12\x17\n\x0f\x63ontainer_index\x18\x02 \x02(\x05\"\x92\x01\n\x15UpdateTopologyRequest\x12;\n\x12\x63urrentPackingPlan\x18\x01 \x02(\x0b\x32\x1f.heron.proto.system.PackingPlan\x12<\n\x13proposedPackingPlan\x18\x02 \x02(\x0b\x32\x1f.heron.proto.system.PackingPlan\"?\n\x11SchedulerResponse\x12*\n\x06status\x18\x01 \x02(\x0b\x32\x1a.heron.proto.system.StatusB.\n!com.twitter.heron.proto.schedulerB\tScheduler')
  ,
  dependencies=[common__pb2.DESCRIPTOR,packing__plan__pb2.DESCRIPTOR,])




_SCHEDULERLOCATION = _descriptor.Descriptor(
  name='SchedulerLocation',
  full_name='heron.proto.scheduler.SchedulerLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.scheduler.SchedulerLocation.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='http_endpoint', full_name='heron.proto.scheduler.SchedulerLocation.http_endpoint', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_page_link', full_name='heron.proto.scheduler.SchedulerLocation.job_page_link', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=164,
)


_KILLTOPOLOGYREQUEST = _descriptor.Descriptor(
  name='KillTopologyRequest',
  full_name='heron.proto.scheduler.KillTopologyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.scheduler.KillTopologyRequest.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=210,
)


_RESTARTTOPOLOGYREQUEST = _descriptor.Descriptor(
  name='RestartTopologyRequest',
  full_name='heron.proto.scheduler.RestartTopologyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.scheduler.RestartTopologyRequest.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_index', full_name='heron.proto.scheduler.RestartTopologyRequest.container_index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=284,
)


_UPDATETOPOLOGYREQUEST = _descriptor.Descriptor(
  name='UpdateTopologyRequest',
  full_name='heron.proto.scheduler.UpdateTopologyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentPackingPlan', full_name='heron.proto.scheduler.UpdateTopologyRequest.currentPackingPlan', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proposedPackingPlan', full_name='heron.proto.scheduler.UpdateTopologyRequest.proposedPackingPlan', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=433,
)


_SCHEDULERRESPONSE = _descriptor.Descriptor(
  name='SchedulerResponse',
  full_name='heron.proto.scheduler.SchedulerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='heron.proto.scheduler.SchedulerResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=498,
)

_UPDATETOPOLOGYREQUEST.fields_by_name['currentPackingPlan'].message_type = packing__plan__pb2._PACKINGPLAN
_UPDATETOPOLOGYREQUEST.fields_by_name['proposedPackingPlan'].message_type = packing__plan__pb2._PACKINGPLAN
_SCHEDULERRESPONSE.fields_by_name['status'].message_type = common__pb2._STATUS
DESCRIPTOR.message_types_by_name['SchedulerLocation'] = _SCHEDULERLOCATION
DESCRIPTOR.message_types_by_name['KillTopologyRequest'] = _KILLTOPOLOGYREQUEST
DESCRIPTOR.message_types_by_name['RestartTopologyRequest'] = _RESTARTTOPOLOGYREQUEST
DESCRIPTOR.message_types_by_name['UpdateTopologyRequest'] = _UPDATETOPOLOGYREQUEST
DESCRIPTOR.message_types_by_name['SchedulerResponse'] = _SCHEDULERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchedulerLocation = _reflection.GeneratedProtocolMessageType('SchedulerLocation', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULERLOCATION,
  __module__ = 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.scheduler.SchedulerLocation)
  ))
_sym_db.RegisterMessage(SchedulerLocation)

KillTopologyRequest = _reflection.GeneratedProtocolMessageType('KillTopologyRequest', (_message.Message,), dict(
  DESCRIPTOR = _KILLTOPOLOGYREQUEST,
  __module__ = 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.scheduler.KillTopologyRequest)
  ))
_sym_db.RegisterMessage(KillTopologyRequest)

RestartTopologyRequest = _reflection.GeneratedProtocolMessageType('RestartTopologyRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESTARTTOPOLOGYREQUEST,
  __module__ = 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.scheduler.RestartTopologyRequest)
  ))
_sym_db.RegisterMessage(RestartTopologyRequest)

UpdateTopologyRequest = _reflection.GeneratedProtocolMessageType('UpdateTopologyRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATETOPOLOGYREQUEST,
  __module__ = 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.scheduler.UpdateTopologyRequest)
  ))
_sym_db.RegisterMessage(UpdateTopologyRequest)

SchedulerResponse = _reflection.GeneratedProtocolMessageType('SchedulerResponse', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULERRESPONSE,
  __module__ = 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.scheduler.SchedulerResponse)
  ))
_sym_db.RegisterMessage(SchedulerResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.twitter.heron.proto.schedulerB\tScheduler'))
# @@protoc_insertion_point(module_scope)
