# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='heron.proto.system',
  syntax='proto2',
  serialized_pb=_b('\n\x0bstats.proto\x12\x12heron.proto.system\"\x0c\n\nStMgrStatsB\'\n\x1e\x63om.twitter.heron.proto.systemB\x05Stats')
)




_STMGRSTATS = _descriptor.Descriptor(
  name='StMgrStats',
  full_name='heron.proto.system.StMgrStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['StMgrStats'] = _STMGRSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StMgrStats = _reflection.GeneratedProtocolMessageType('StMgrStats', (_message.Message,), dict(
  DESCRIPTOR = _STMGRSTATS,
  __module__ = 'stats_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.StMgrStats)
  ))
_sym_db.RegisterMessage(StMgrStats)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.twitter.heron.proto.systemB\005Stats'))
# @@protoc_insertion_point(module_scope)
