# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import tmaster_pb2 as tmaster__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metrics.proto',
  package='heron.proto.system',
  syntax='proto2',
  serialized_pb=_b('\n\rmetrics.proto\x12\x12heron.proto.system\x1a\x0c\x63ommon.proto\x1a\rtmaster.proto\"*\n\x0bMetricDatum\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"h\n\rExceptionData\x12\x12\n\nstacktrace\x18\x01 \x02(\t\x12\x10\n\x08lasttime\x18\x02 \x02(\t\x12\x11\n\tfirsttime\x18\x03 \x02(\t\x12\r\n\x05\x63ount\x18\x04 \x02(\x05\x12\x0f\n\x07logging\x18\x05 \x02(\t\"v\n\x0fMetricPublisher\x12\x10\n\x08hostname\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\x05\x12\x16\n\x0e\x63omponent_name\x18\x03 \x02(\t\x12\x13\n\x0binstance_id\x18\x04 \x02(\t\x12\x16\n\x0einstance_index\x18\x05 \x02(\x05\"X\n\x1eMetricPublisherRegisterRequest\x12\x36\n\tpublisher\x18\x01 \x02(\x0b\x32#.heron.proto.system.MetricPublisher\"M\n\x1fMetricPublisherRegisterResponse\x12*\n\x06status\x18\x01 \x02(\x0b\x32\x1a.heron.proto.system.Status\"\x88\x01\n\x1dMetricPublisherPublishMessage\x12\x30\n\x07metrics\x18\x01 \x03(\x0b\x32\x1f.heron.proto.system.MetricDatum\x12\x35\n\nexceptions\x18\x02 \x03(\x0b\x32!.heron.proto.system.ExceptionData\"V\n\x1dTMasterLocationRefreshMessage\x12\x35\n\x07tmaster\x18\x01 \x02(\x0b\x32$.heron.proto.tmaster.TMasterLocation\"e\n\"MetricsCacheLocationRefreshMessage\x12?\n\x0cmetricscache\x18\x01 \x02(\x0b\x32).heron.proto.tmaster.MetricsCacheLocationB)\n\x1e\x63om.twitter.heron.proto.systemB\x07Metrics')
  ,
  dependencies=[common__pb2.DESCRIPTOR,tmaster__pb2.DESCRIPTOR,])




_METRICDATUM = _descriptor.Descriptor(
  name='MetricDatum',
  full_name='heron.proto.system.MetricDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='heron.proto.system.MetricDatum.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='heron.proto.system.MetricDatum.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=108,
)


_EXCEPTIONDATA = _descriptor.Descriptor(
  name='ExceptionData',
  full_name='heron.proto.system.ExceptionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stacktrace', full_name='heron.proto.system.ExceptionData.stacktrace', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lasttime', full_name='heron.proto.system.ExceptionData.lasttime', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firsttime', full_name='heron.proto.system.ExceptionData.firsttime', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='heron.proto.system.ExceptionData.count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logging', full_name='heron.proto.system.ExceptionData.logging', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=214,
)


_METRICPUBLISHER = _descriptor.Descriptor(
  name='MetricPublisher',
  full_name='heron.proto.system.MetricPublisher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='heron.proto.system.MetricPublisher.hostname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='heron.proto.system.MetricPublisher.port', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_name', full_name='heron.proto.system.MetricPublisher.component_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='heron.proto.system.MetricPublisher.instance_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_index', full_name='heron.proto.system.MetricPublisher.instance_index', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=334,
)


_METRICPUBLISHERREGISTERREQUEST = _descriptor.Descriptor(
  name='MetricPublisherRegisterRequest',
  full_name='heron.proto.system.MetricPublisherRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publisher', full_name='heron.proto.system.MetricPublisherRegisterRequest.publisher', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=424,
)


_METRICPUBLISHERREGISTERRESPONSE = _descriptor.Descriptor(
  name='MetricPublisherRegisterResponse',
  full_name='heron.proto.system.MetricPublisherRegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='heron.proto.system.MetricPublisherRegisterResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=503,
)


_METRICPUBLISHERPUBLISHMESSAGE = _descriptor.Descriptor(
  name='MetricPublisherPublishMessage',
  full_name='heron.proto.system.MetricPublisherPublishMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='heron.proto.system.MetricPublisherPublishMessage.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exceptions', full_name='heron.proto.system.MetricPublisherPublishMessage.exceptions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=642,
)


_TMASTERLOCATIONREFRESHMESSAGE = _descriptor.Descriptor(
  name='TMasterLocationRefreshMessage',
  full_name='heron.proto.system.TMasterLocationRefreshMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmaster', full_name='heron.proto.system.TMasterLocationRefreshMessage.tmaster', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=730,
)


_METRICSCACHELOCATIONREFRESHMESSAGE = _descriptor.Descriptor(
  name='MetricsCacheLocationRefreshMessage',
  full_name='heron.proto.system.MetricsCacheLocationRefreshMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metricscache', full_name='heron.proto.system.MetricsCacheLocationRefreshMessage.metricscache', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=833,
)

_METRICPUBLISHERREGISTERREQUEST.fields_by_name['publisher'].message_type = _METRICPUBLISHER
_METRICPUBLISHERREGISTERRESPONSE.fields_by_name['status'].message_type = common__pb2._STATUS
_METRICPUBLISHERPUBLISHMESSAGE.fields_by_name['metrics'].message_type = _METRICDATUM
_METRICPUBLISHERPUBLISHMESSAGE.fields_by_name['exceptions'].message_type = _EXCEPTIONDATA
_TMASTERLOCATIONREFRESHMESSAGE.fields_by_name['tmaster'].message_type = tmaster__pb2._TMASTERLOCATION
_METRICSCACHELOCATIONREFRESHMESSAGE.fields_by_name['metricscache'].message_type = tmaster__pb2._METRICSCACHELOCATION
DESCRIPTOR.message_types_by_name['MetricDatum'] = _METRICDATUM
DESCRIPTOR.message_types_by_name['ExceptionData'] = _EXCEPTIONDATA
DESCRIPTOR.message_types_by_name['MetricPublisher'] = _METRICPUBLISHER
DESCRIPTOR.message_types_by_name['MetricPublisherRegisterRequest'] = _METRICPUBLISHERREGISTERREQUEST
DESCRIPTOR.message_types_by_name['MetricPublisherRegisterResponse'] = _METRICPUBLISHERREGISTERRESPONSE
DESCRIPTOR.message_types_by_name['MetricPublisherPublishMessage'] = _METRICPUBLISHERPUBLISHMESSAGE
DESCRIPTOR.message_types_by_name['TMasterLocationRefreshMessage'] = _TMASTERLOCATIONREFRESHMESSAGE
DESCRIPTOR.message_types_by_name['MetricsCacheLocationRefreshMessage'] = _METRICSCACHELOCATIONREFRESHMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricDatum = _reflection.GeneratedProtocolMessageType('MetricDatum', (_message.Message,), dict(
  DESCRIPTOR = _METRICDATUM,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.MetricDatum)
  ))
_sym_db.RegisterMessage(MetricDatum)

ExceptionData = _reflection.GeneratedProtocolMessageType('ExceptionData', (_message.Message,), dict(
  DESCRIPTOR = _EXCEPTIONDATA,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.ExceptionData)
  ))
_sym_db.RegisterMessage(ExceptionData)

MetricPublisher = _reflection.GeneratedProtocolMessageType('MetricPublisher', (_message.Message,), dict(
  DESCRIPTOR = _METRICPUBLISHER,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.MetricPublisher)
  ))
_sym_db.RegisterMessage(MetricPublisher)

MetricPublisherRegisterRequest = _reflection.GeneratedProtocolMessageType('MetricPublisherRegisterRequest', (_message.Message,), dict(
  DESCRIPTOR = _METRICPUBLISHERREGISTERREQUEST,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.MetricPublisherRegisterRequest)
  ))
_sym_db.RegisterMessage(MetricPublisherRegisterRequest)

MetricPublisherRegisterResponse = _reflection.GeneratedProtocolMessageType('MetricPublisherRegisterResponse', (_message.Message,), dict(
  DESCRIPTOR = _METRICPUBLISHERREGISTERRESPONSE,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.MetricPublisherRegisterResponse)
  ))
_sym_db.RegisterMessage(MetricPublisherRegisterResponse)

MetricPublisherPublishMessage = _reflection.GeneratedProtocolMessageType('MetricPublisherPublishMessage', (_message.Message,), dict(
  DESCRIPTOR = _METRICPUBLISHERPUBLISHMESSAGE,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.MetricPublisherPublishMessage)
  ))
_sym_db.RegisterMessage(MetricPublisherPublishMessage)

TMasterLocationRefreshMessage = _reflection.GeneratedProtocolMessageType('TMasterLocationRefreshMessage', (_message.Message,), dict(
  DESCRIPTOR = _TMASTERLOCATIONREFRESHMESSAGE,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.TMasterLocationRefreshMessage)
  ))
_sym_db.RegisterMessage(TMasterLocationRefreshMessage)

MetricsCacheLocationRefreshMessage = _reflection.GeneratedProtocolMessageType('MetricsCacheLocationRefreshMessage', (_message.Message,), dict(
  DESCRIPTOR = _METRICSCACHELOCATIONREFRESHMESSAGE,
  __module__ = 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.MetricsCacheLocationRefreshMessage)
  ))
_sym_db.RegisterMessage(MetricsCacheLocationRefreshMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.twitter.heron.proto.systemB\007Metrics'))
# @@protoc_insertion_point(module_scope)
