# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packing_plan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packing_plan.proto',
  package='heron.proto.system',
  syntax='proto2',
  serialized_pb=_b('\n\x12packing_plan.proto\x12\x12heron.proto.system\"2\n\x08Resource\x12\x0b\n\x03\x63pu\x18\x01 \x02(\x01\x12\x0b\n\x03ram\x18\x02 \x02(\x03\x12\x0c\n\x04\x64isk\x18\x03 \x02(\x03\"\x80\x01\n\x0cInstancePlan\x12\x16\n\x0e\x63omponent_name\x18\x01 \x02(\t\x12\x0f\n\x07task_id\x18\x02 \x02(\x05\x12\x17\n\x0f\x63omponent_index\x18\x03 \x02(\x05\x12.\n\x08resource\x18\x04 \x02(\x0b\x32\x1c.heron.proto.system.Resource\"\xc6\x01\n\rContainerPlan\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x38\n\x0einstance_plans\x18\x02 \x03(\x0b\x32 .heron.proto.system.InstancePlan\x12\x36\n\x10requiredResource\x18\x03 \x02(\x0b\x32\x1c.heron.proto.system.Resource\x12\x37\n\x11scheduledResource\x18\x04 \x01(\x0b\x32\x1c.heron.proto.system.Resource\"U\n\x0bPackingPlan\x12\n\n\x02id\x18\x01 \x02(\t\x12:\n\x0f\x63ontainer_plans\x18\x02 \x03(\x0b\x32!.heron.proto.system.ContainerPlanB.\n\x1e\x63om.twitter.heron.proto.systemB\x0cPackingPlans')
)




_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='heron.proto.system.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='heron.proto.system.Resource.cpu', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ram', full_name='heron.proto.system.Resource.ram', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk', full_name='heron.proto.system.Resource.disk', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=92,
)


_INSTANCEPLAN = _descriptor.Descriptor(
  name='InstancePlan',
  full_name='heron.proto.system.InstancePlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component_name', full_name='heron.proto.system.InstancePlan.component_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='heron.proto.system.InstancePlan.task_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component_index', full_name='heron.proto.system.InstancePlan.component_index', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource', full_name='heron.proto.system.InstancePlan.resource', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=223,
)


_CONTAINERPLAN = _descriptor.Descriptor(
  name='ContainerPlan',
  full_name='heron.proto.system.ContainerPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='heron.proto.system.ContainerPlan.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_plans', full_name='heron.proto.system.ContainerPlan.instance_plans', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requiredResource', full_name='heron.proto.system.ContainerPlan.requiredResource', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scheduledResource', full_name='heron.proto.system.ContainerPlan.scheduledResource', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=424,
)


_PACKINGPLAN = _descriptor.Descriptor(
  name='PackingPlan',
  full_name='heron.proto.system.PackingPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='heron.proto.system.PackingPlan.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_plans', full_name='heron.proto.system.PackingPlan.container_plans', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=511,
)

_INSTANCEPLAN.fields_by_name['resource'].message_type = _RESOURCE
_CONTAINERPLAN.fields_by_name['instance_plans'].message_type = _INSTANCEPLAN
_CONTAINERPLAN.fields_by_name['requiredResource'].message_type = _RESOURCE
_CONTAINERPLAN.fields_by_name['scheduledResource'].message_type = _RESOURCE
_PACKINGPLAN.fields_by_name['container_plans'].message_type = _CONTAINERPLAN
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
DESCRIPTOR.message_types_by_name['InstancePlan'] = _INSTANCEPLAN
DESCRIPTOR.message_types_by_name['ContainerPlan'] = _CONTAINERPLAN
DESCRIPTOR.message_types_by_name['PackingPlan'] = _PACKINGPLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCE,
  __module__ = 'packing_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.Resource)
  ))
_sym_db.RegisterMessage(Resource)

InstancePlan = _reflection.GeneratedProtocolMessageType('InstancePlan', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCEPLAN,
  __module__ = 'packing_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.InstancePlan)
  ))
_sym_db.RegisterMessage(InstancePlan)

ContainerPlan = _reflection.GeneratedProtocolMessageType('ContainerPlan', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERPLAN,
  __module__ = 'packing_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.ContainerPlan)
  ))
_sym_db.RegisterMessage(ContainerPlan)

PackingPlan = _reflection.GeneratedProtocolMessageType('PackingPlan', (_message.Message,), dict(
  DESCRIPTOR = _PACKINGPLAN,
  __module__ = 'packing_plan_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.PackingPlan)
  ))
_sym_db.RegisterMessage(PackingPlan)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.twitter.heron.proto.systemB\014PackingPlans'))
# @@protoc_insertion_point(module_scope)
