# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stmgr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import physical_plan_pb2 as physical__plan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stmgr.proto',
  package='heron.proto.stmgr',
  syntax='proto2',
  serialized_pb=_b('\n\x0bstmgr.proto\x12\x11heron.proto.stmgr\x1a\x0c\x63ommon.proto\x1a\x13physical_plan.proto\"M\n\x16NewPhysicalPlanMessage\x12\x33\n\tnew_pplan\x18\x01 \x02(\x0b\x32 .heron.proto.system.PhysicalPlan\"u\n\x17RegisterInstanceRequest\x12.\n\x08instance\x18\x01 \x02(\x0b\x32\x1c.heron.proto.system.Instance\x12\x15\n\rtopology_name\x18\x02 \x02(\t\x12\x13\n\x0btopology_id\x18\x03 \x02(\t\"w\n\x18RegisterInstanceResponse\x12*\n\x06status\x18\x01 \x02(\x0b\x32\x1a.heron.proto.system.Status\x12/\n\x05pplan\x18\x02 \x01(\x0b\x32 .heron.proto.system.PhysicalPlan\"O\n\x1cNewInstanceAssignmentMessage\x12/\n\x05pplan\x18\x01 \x02(\x0b\x32 .heron.proto.system.PhysicalPlan\"O\n\x12StrMgrHelloRequest\x12\x15\n\rtopology_name\x18\x01 \x02(\t\x12\x13\n\x0btopology_id\x18\x02 \x02(\t\x12\r\n\x05stmgr\x18\x03 \x02(\t\"A\n\x13StrMgrHelloResponse\x12*\n\x06status\x18\x01 \x02(\x0b\x32\x1a.heron.proto.system.Status\"i\n\x18StartBackPressureMessage\x12\x15\n\rtopology_name\x18\x01 \x02(\t\x12\x13\n\x0btopology_id\x18\x02 \x02(\t\x12\r\n\x05stmgr\x18\x03 \x02(\t\x12\x12\n\nmessage_id\x18\x04 \x02(\t\"h\n\x17StopBackPressureMessage\x12\x15\n\rtopology_name\x18\x01 \x02(\t\x12\x13\n\x0btopology_id\x18\x02 \x02(\t\x12\r\n\x05stmgr\x18\x03 \x02(\t\x12\x12\n\nmessage_id\x18\x04 \x02(\t\"G\n\x12TupleStreamMessage\x12\x13\n\x0bsrc_task_id\x18\x03 \x02(\x05\x12\x0f\n\x07task_id\x18\x01 \x02(\x05\x12\x0b\n\x03set\x18\x02 \x02(\x0c\x42.\n\x1d\x63om.twitter.heron.proto.stmgrB\rStreamManager')
  ,
  dependencies=[common__pb2.DESCRIPTOR,physical__plan__pb2.DESCRIPTOR,])




_NEWPHYSICALPLANMESSAGE = _descriptor.Descriptor(
  name='NewPhysicalPlanMessage',
  full_name='heron.proto.stmgr.NewPhysicalPlanMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_pplan', full_name='heron.proto.stmgr.NewPhysicalPlanMessage.new_pplan', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=146,
)


_REGISTERINSTANCEREQUEST = _descriptor.Descriptor(
  name='RegisterInstanceRequest',
  full_name='heron.proto.stmgr.RegisterInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='heron.proto.stmgr.RegisterInstanceRequest.instance', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.stmgr.RegisterInstanceRequest.topology_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topology_id', full_name='heron.proto.stmgr.RegisterInstanceRequest.topology_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=265,
)


_REGISTERINSTANCERESPONSE = _descriptor.Descriptor(
  name='RegisterInstanceResponse',
  full_name='heron.proto.stmgr.RegisterInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='heron.proto.stmgr.RegisterInstanceResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pplan', full_name='heron.proto.stmgr.RegisterInstanceResponse.pplan', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=386,
)


_NEWINSTANCEASSIGNMENTMESSAGE = _descriptor.Descriptor(
  name='NewInstanceAssignmentMessage',
  full_name='heron.proto.stmgr.NewInstanceAssignmentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pplan', full_name='heron.proto.stmgr.NewInstanceAssignmentMessage.pplan', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=467,
)


_STRMGRHELLOREQUEST = _descriptor.Descriptor(
  name='StrMgrHelloRequest',
  full_name='heron.proto.stmgr.StrMgrHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.stmgr.StrMgrHelloRequest.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topology_id', full_name='heron.proto.stmgr.StrMgrHelloRequest.topology_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgr', full_name='heron.proto.stmgr.StrMgrHelloRequest.stmgr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=548,
)


_STRMGRHELLORESPONSE = _descriptor.Descriptor(
  name='StrMgrHelloResponse',
  full_name='heron.proto.stmgr.StrMgrHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='heron.proto.stmgr.StrMgrHelloResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=615,
)


_STARTBACKPRESSUREMESSAGE = _descriptor.Descriptor(
  name='StartBackPressureMessage',
  full_name='heron.proto.stmgr.StartBackPressureMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.stmgr.StartBackPressureMessage.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topology_id', full_name='heron.proto.stmgr.StartBackPressureMessage.topology_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgr', full_name='heron.proto.stmgr.StartBackPressureMessage.stmgr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='heron.proto.stmgr.StartBackPressureMessage.message_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=722,
)


_STOPBACKPRESSUREMESSAGE = _descriptor.Descriptor(
  name='StopBackPressureMessage',
  full_name='heron.proto.stmgr.StopBackPressureMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topology_name', full_name='heron.proto.stmgr.StopBackPressureMessage.topology_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topology_id', full_name='heron.proto.stmgr.StopBackPressureMessage.topology_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmgr', full_name='heron.proto.stmgr.StopBackPressureMessage.stmgr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='heron.proto.stmgr.StopBackPressureMessage.message_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=828,
)


_TUPLESTREAMMESSAGE = _descriptor.Descriptor(
  name='TupleStreamMessage',
  full_name='heron.proto.stmgr.TupleStreamMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_task_id', full_name='heron.proto.stmgr.TupleStreamMessage.src_task_id', index=0,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='heron.proto.stmgr.TupleStreamMessage.task_id', index=1,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set', full_name='heron.proto.stmgr.TupleStreamMessage.set', index=2,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=901,
)

_NEWPHYSICALPLANMESSAGE.fields_by_name['new_pplan'].message_type = physical__plan__pb2._PHYSICALPLAN
_REGISTERINSTANCEREQUEST.fields_by_name['instance'].message_type = physical__plan__pb2._INSTANCE
_REGISTERINSTANCERESPONSE.fields_by_name['status'].message_type = common__pb2._STATUS
_REGISTERINSTANCERESPONSE.fields_by_name['pplan'].message_type = physical__plan__pb2._PHYSICALPLAN
_NEWINSTANCEASSIGNMENTMESSAGE.fields_by_name['pplan'].message_type = physical__plan__pb2._PHYSICALPLAN
_STRMGRHELLORESPONSE.fields_by_name['status'].message_type = common__pb2._STATUS
DESCRIPTOR.message_types_by_name['NewPhysicalPlanMessage'] = _NEWPHYSICALPLANMESSAGE
DESCRIPTOR.message_types_by_name['RegisterInstanceRequest'] = _REGISTERINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['RegisterInstanceResponse'] = _REGISTERINSTANCERESPONSE
DESCRIPTOR.message_types_by_name['NewInstanceAssignmentMessage'] = _NEWINSTANCEASSIGNMENTMESSAGE
DESCRIPTOR.message_types_by_name['StrMgrHelloRequest'] = _STRMGRHELLOREQUEST
DESCRIPTOR.message_types_by_name['StrMgrHelloResponse'] = _STRMGRHELLORESPONSE
DESCRIPTOR.message_types_by_name['StartBackPressureMessage'] = _STARTBACKPRESSUREMESSAGE
DESCRIPTOR.message_types_by_name['StopBackPressureMessage'] = _STOPBACKPRESSUREMESSAGE
DESCRIPTOR.message_types_by_name['TupleStreamMessage'] = _TUPLESTREAMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewPhysicalPlanMessage = _reflection.GeneratedProtocolMessageType('NewPhysicalPlanMessage', (_message.Message,), dict(
  DESCRIPTOR = _NEWPHYSICALPLANMESSAGE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.NewPhysicalPlanMessage)
  ))
_sym_db.RegisterMessage(NewPhysicalPlanMessage)

RegisterInstanceRequest = _reflection.GeneratedProtocolMessageType('RegisterInstanceRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERINSTANCEREQUEST,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.RegisterInstanceRequest)
  ))
_sym_db.RegisterMessage(RegisterInstanceRequest)

RegisterInstanceResponse = _reflection.GeneratedProtocolMessageType('RegisterInstanceResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERINSTANCERESPONSE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.RegisterInstanceResponse)
  ))
_sym_db.RegisterMessage(RegisterInstanceResponse)

NewInstanceAssignmentMessage = _reflection.GeneratedProtocolMessageType('NewInstanceAssignmentMessage', (_message.Message,), dict(
  DESCRIPTOR = _NEWINSTANCEASSIGNMENTMESSAGE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.NewInstanceAssignmentMessage)
  ))
_sym_db.RegisterMessage(NewInstanceAssignmentMessage)

StrMgrHelloRequest = _reflection.GeneratedProtocolMessageType('StrMgrHelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRMGRHELLOREQUEST,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.StrMgrHelloRequest)
  ))
_sym_db.RegisterMessage(StrMgrHelloRequest)

StrMgrHelloResponse = _reflection.GeneratedProtocolMessageType('StrMgrHelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRMGRHELLORESPONSE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.StrMgrHelloResponse)
  ))
_sym_db.RegisterMessage(StrMgrHelloResponse)

StartBackPressureMessage = _reflection.GeneratedProtocolMessageType('StartBackPressureMessage', (_message.Message,), dict(
  DESCRIPTOR = _STARTBACKPRESSUREMESSAGE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.StartBackPressureMessage)
  ))
_sym_db.RegisterMessage(StartBackPressureMessage)

StopBackPressureMessage = _reflection.GeneratedProtocolMessageType('StopBackPressureMessage', (_message.Message,), dict(
  DESCRIPTOR = _STOPBACKPRESSUREMESSAGE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.StopBackPressureMessage)
  ))
_sym_db.RegisterMessage(StopBackPressureMessage)

TupleStreamMessage = _reflection.GeneratedProtocolMessageType('TupleStreamMessage', (_message.Message,), dict(
  DESCRIPTOR = _TUPLESTREAMMESSAGE,
  __module__ = 'stmgr_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.stmgr.TupleStreamMessage)
  ))
_sym_db.RegisterMessage(TupleStreamMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035com.twitter.heron.proto.stmgrB\rStreamManager'))
# @@protoc_insertion_point(module_scope)
