# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tuple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import topology_pb2 as topology__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tuple.proto',
  package='heron.proto.system',
  syntax='proto2',
  serialized_pb=_b('\n\x0btuple.proto\x12\x12heron.proto.system\x1a\x0etopology.proto\"%\n\x06RootId\x12\x0e\n\x06taskid\x18\x01 \x02(\x05\x12\x0b\n\x03key\x18\x02 \x02(\x10\"I\n\x08\x41\x63kTuple\x12)\n\x05roots\x18\x01 \x03(\x0b\x32\x1a.heron.proto.system.RootId\x12\x12\n\nackedtuple\x18\x02 \x02(\x10\"o\n\x0eHeronDataTuple\x12\x0b\n\x03key\x18\x01 \x02(\x10\x12)\n\x05roots\x18\x02 \x03(\x0b\x32\x1a.heron.proto.system.RootId\x12\x0e\n\x06values\x18\x03 \x03(\x0c\x12\x15\n\rdest_task_ids\x18\x04 \x03(\x05\"r\n\x11HeronDataTupleSet\x12)\n\x06stream\x18\x01 \x02(\x0b\x32\x19.heron.proto.api.StreamId\x12\x32\n\x06tuples\x18\x02 \x03(\x0b\x32\".heron.proto.system.HeronDataTuple\"\x9c\x01\n\x14HeronControlTupleSet\x12*\n\x04\x61\x63ks\x18\x01 \x03(\x0b\x32\x1c.heron.proto.system.AckTuple\x12+\n\x05\x66\x61ils\x18\x02 \x03(\x0b\x32\x1c.heron.proto.system.AckTuple\x12+\n\x05\x65mits\x18\x03 \x03(\x0b\x32\x1c.heron.proto.system.AckTuple\"\x94\x01\n\rHeronTupleSet\x12\x33\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32%.heron.proto.system.HeronDataTupleSet\x12\x39\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32(.heron.proto.system.HeronControlTupleSet\x12\x13\n\x0bsrc_task_id\x18\x03 \x02(\x05\"O\n\x12HeronDataTupleSet2\x12)\n\x06stream\x18\x01 \x02(\x0b\x32\x19.heron.proto.api.StreamId\x12\x0e\n\x06tuples\x18\x02 \x03(\x0c\"\x96\x01\n\x0eHeronTupleSet2\x12\x34\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32&.heron.proto.system.HeronDataTupleSet2\x12\x39\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32(.heron.proto.system.HeronControlTupleSet\x12\x13\n\x0bsrc_task_id\x18\x03 \x02(\x05\x42-\n\x1e\x63om.twitter.heron.proto.systemB\x0bHeronTuples')
  ,
  dependencies=[topology__pb2.DESCRIPTOR,])




_ROOTID = _descriptor.Descriptor(
  name='RootId',
  full_name='heron.proto.system.RootId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskid', full_name='heron.proto.system.RootId.taskid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='heron.proto.system.RootId.key', index=1,
      number=2, type=16, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=88,
)


_ACKTUPLE = _descriptor.Descriptor(
  name='AckTuple',
  full_name='heron.proto.system.AckTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roots', full_name='heron.proto.system.AckTuple.roots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ackedtuple', full_name='heron.proto.system.AckTuple.ackedtuple', index=1,
      number=2, type=16, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=163,
)


_HERONDATATUPLE = _descriptor.Descriptor(
  name='HeronDataTuple',
  full_name='heron.proto.system.HeronDataTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='heron.proto.system.HeronDataTuple.key', index=0,
      number=1, type=16, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roots', full_name='heron.proto.system.HeronDataTuple.roots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='heron.proto.system.HeronDataTuple.values', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_task_ids', full_name='heron.proto.system.HeronDataTuple.dest_task_ids', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=276,
)


_HERONDATATUPLESET = _descriptor.Descriptor(
  name='HeronDataTupleSet',
  full_name='heron.proto.system.HeronDataTupleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='heron.proto.system.HeronDataTupleSet.stream', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tuples', full_name='heron.proto.system.HeronDataTupleSet.tuples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=392,
)


_HERONCONTROLTUPLESET = _descriptor.Descriptor(
  name='HeronControlTupleSet',
  full_name='heron.proto.system.HeronControlTupleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acks', full_name='heron.proto.system.HeronControlTupleSet.acks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fails', full_name='heron.proto.system.HeronControlTupleSet.fails', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emits', full_name='heron.proto.system.HeronControlTupleSet.emits', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=551,
)


_HERONTUPLESET = _descriptor.Descriptor(
  name='HeronTupleSet',
  full_name='heron.proto.system.HeronTupleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='heron.proto.system.HeronTupleSet.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control', full_name='heron.proto.system.HeronTupleSet.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_task_id', full_name='heron.proto.system.HeronTupleSet.src_task_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=702,
)


_HERONDATATUPLESET2 = _descriptor.Descriptor(
  name='HeronDataTupleSet2',
  full_name='heron.proto.system.HeronDataTupleSet2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='heron.proto.system.HeronDataTupleSet2.stream', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tuples', full_name='heron.proto.system.HeronDataTupleSet2.tuples', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=783,
)


_HERONTUPLESET2 = _descriptor.Descriptor(
  name='HeronTupleSet2',
  full_name='heron.proto.system.HeronTupleSet2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='heron.proto.system.HeronTupleSet2.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control', full_name='heron.proto.system.HeronTupleSet2.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_task_id', full_name='heron.proto.system.HeronTupleSet2.src_task_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=786,
  serialized_end=936,
)

_ACKTUPLE.fields_by_name['roots'].message_type = _ROOTID
_HERONDATATUPLE.fields_by_name['roots'].message_type = _ROOTID
_HERONDATATUPLESET.fields_by_name['stream'].message_type = topology__pb2._STREAMID
_HERONDATATUPLESET.fields_by_name['tuples'].message_type = _HERONDATATUPLE
_HERONCONTROLTUPLESET.fields_by_name['acks'].message_type = _ACKTUPLE
_HERONCONTROLTUPLESET.fields_by_name['fails'].message_type = _ACKTUPLE
_HERONCONTROLTUPLESET.fields_by_name['emits'].message_type = _ACKTUPLE
_HERONTUPLESET.fields_by_name['data'].message_type = _HERONDATATUPLESET
_HERONTUPLESET.fields_by_name['control'].message_type = _HERONCONTROLTUPLESET
_HERONDATATUPLESET2.fields_by_name['stream'].message_type = topology__pb2._STREAMID
_HERONTUPLESET2.fields_by_name['data'].message_type = _HERONDATATUPLESET2
_HERONTUPLESET2.fields_by_name['control'].message_type = _HERONCONTROLTUPLESET
DESCRIPTOR.message_types_by_name['RootId'] = _ROOTID
DESCRIPTOR.message_types_by_name['AckTuple'] = _ACKTUPLE
DESCRIPTOR.message_types_by_name['HeronDataTuple'] = _HERONDATATUPLE
DESCRIPTOR.message_types_by_name['HeronDataTupleSet'] = _HERONDATATUPLESET
DESCRIPTOR.message_types_by_name['HeronControlTupleSet'] = _HERONCONTROLTUPLESET
DESCRIPTOR.message_types_by_name['HeronTupleSet'] = _HERONTUPLESET
DESCRIPTOR.message_types_by_name['HeronDataTupleSet2'] = _HERONDATATUPLESET2
DESCRIPTOR.message_types_by_name['HeronTupleSet2'] = _HERONTUPLESET2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RootId = _reflection.GeneratedProtocolMessageType('RootId', (_message.Message,), dict(
  DESCRIPTOR = _ROOTID,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.RootId)
  ))
_sym_db.RegisterMessage(RootId)

AckTuple = _reflection.GeneratedProtocolMessageType('AckTuple', (_message.Message,), dict(
  DESCRIPTOR = _ACKTUPLE,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.AckTuple)
  ))
_sym_db.RegisterMessage(AckTuple)

HeronDataTuple = _reflection.GeneratedProtocolMessageType('HeronDataTuple', (_message.Message,), dict(
  DESCRIPTOR = _HERONDATATUPLE,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronDataTuple)
  ))
_sym_db.RegisterMessage(HeronDataTuple)

HeronDataTupleSet = _reflection.GeneratedProtocolMessageType('HeronDataTupleSet', (_message.Message,), dict(
  DESCRIPTOR = _HERONDATATUPLESET,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronDataTupleSet)
  ))
_sym_db.RegisterMessage(HeronDataTupleSet)

HeronControlTupleSet = _reflection.GeneratedProtocolMessageType('HeronControlTupleSet', (_message.Message,), dict(
  DESCRIPTOR = _HERONCONTROLTUPLESET,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronControlTupleSet)
  ))
_sym_db.RegisterMessage(HeronControlTupleSet)

HeronTupleSet = _reflection.GeneratedProtocolMessageType('HeronTupleSet', (_message.Message,), dict(
  DESCRIPTOR = _HERONTUPLESET,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronTupleSet)
  ))
_sym_db.RegisterMessage(HeronTupleSet)

HeronDataTupleSet2 = _reflection.GeneratedProtocolMessageType('HeronDataTupleSet2', (_message.Message,), dict(
  DESCRIPTOR = _HERONDATATUPLESET2,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronDataTupleSet2)
  ))
_sym_db.RegisterMessage(HeronDataTupleSet2)

HeronTupleSet2 = _reflection.GeneratedProtocolMessageType('HeronTupleSet2', (_message.Message,), dict(
  DESCRIPTOR = _HERONTUPLESET2,
  __module__ = 'tuple_pb2'
  # @@protoc_insertion_point(class_scope:heron.proto.system.HeronTupleSet2)
  ))
_sym_db.RegisterMessage(HeronTupleSet2)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.twitter.heron.proto.systemB\013HeronTuples'))
# @@protoc_insertion_point(module_scope)
